#!/bin/bash
clear
echo -n "Insira um mes de 1 a 12: ";read mes;
if [ $mes -ge 1 -a $mes -le 12 ]
then 
 echo "Insira um ano com 4 digitos: "; read ano;
 if [ $ano -ge 0 -a $ano -le 9999 ]
 then 
  cal $mes $ano
 else
  echo "Ano invalido"
 fi
else 
 echo "Mes invalido"
fi
